# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: info
cmd/husky:
  host: localhost:4443
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 4443
    certPath: cmd/husky/.testdata/localhost.crt
    keyPath: cmd/husky/.testdata/localhost.key
  wintr/auth/ice:
    jwtSecret: bogus
cmd/husky-pack:
  host: localhost:5443
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 5443
    certPath: cmd/husky-pack/.testdata/localhost.crt
    keyPath: cmd/husky-pack/.testdata/localhost.key
  wintr/auth/ice:
    jwtSecret: bogus
news: &news
  db: &newsDatabase
    urls:
      - localhost:3501
    user: admin
    password: pass
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5434/husky
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5434/husky
  messageBroker: &newsMessageBroker
    consumerGroup: husky-local-news-testing
    createTopics: true
    urls:
      - localhost:9092
    topics: &newsTopics
      - name: husky-news-health-check
        partitions: 1
        replicationFactor: 1
        retention: 1000h
      - name: news-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: viewed-news
        partitions: 10
        replicationFactor: 1
        retention: 1000h
  wintr/multimedia/picture:
    urlUpload: https://storage.bunnycdn.com/ice-staging/news
    urlDownload: https://ice-staging.b-cdn.net/news
analytics: &analytics
  wintr/analytics/tracking:
    baseUrl: https://api-02.moengage.com
  db: &analyticsDatabase
    urls:
      - localhost:3501
    user: admin
    password: pass
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5434/husky
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5434/husky
  messageBroker: &analyticsMessageBroker
    consumerGroup: husky-local-analytics-testing
    createTopics: true
    urls:
      - localhost:9092
    topics: &analyticsTopics
      - name: analytics-set-attributes
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: analytics-track-action
        partitions: 10
        replicationFactor: 1
        retention: 1000h
    consumingTopics:
      - name: analytics-set-attributes
        oneGoroutinePerPartition: true
      - name: analytics-track-action
        oneGoroutinePerPartition: true
notifications: &notifications
  deeplinkScheme: staging.ice.app
  pingCooldown: 1m
  disabledAchievementsNotifications:
    levels:
      - l6
    badges:
      - s1
      - c1
      - l1
  notificationDelays:
    news_en_v2:
      maxDelay: 60
      minDelay: 20
  wintr/multimedia/picture:
    urlDownload: https://ice-staging.b-cdn.net
  db: &notificationsDatabase
    urls:
      - localhost:3501
    user: admin
    password: pass
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5434/husky
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5434/husky
  messageBroker: &notificationsMessageBroker
    consumerGroup: husky-local-notifications-testing
    createTopics: true
    urls:
      - localhost:9092
    topics: &notificationsMessageBrokerTopics
      - name: husky-notifications-health-check
        partitions: 1
        replicationFactor: 1
        retention: 1000h
      - name: user-pings
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      ### The next topics are not owned by this service, but are needed to be created for the local/test environment.
      - name: users-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: user-device-metadata-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: adoption-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: news-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: available-daily-bonuses
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: started-days-off
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name:  achieved-badges
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: completed-levels
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: enabled-roles
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: contacts-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
    consumingTopics:
      - name: users-table
      - name: user-device-metadata-table
      - name: adoption-table
      - name: news-table
      - name: available-daily-bonuses
      - name: user-pings
      - name: started-days-off
      - name: achieved-badges
      - name: completed-levels
      - name: enabled-roles
      - name: contacts-table
    producingTopics:
      - name: analytics-set-attributes
      - name: analytics-track-action
notifications_test:
  <<: *notifications
  messageBroker:
    <<: *notificationsMessageBroker
    consumingTopics: *notificationsMessageBrokerTopics
    consumerGroup: husky-local-notifications-test
  db:
    <<: *notificationsDatabase
news_test:
  <<: *news
  messageBroker:
    <<: *newsMessageBroker
    consumingTopics: *newsTopics
    consumerGroup: husky-local-news-test
  db:
    <<: *newsDatabase
analytics_test:
  <<: *analytics
  messageBroker:
    <<: *analyticsMessageBroker
    consumingTopics: *analyticsTopics
    consumerGroup: husky-local-analytics-test
  db:
    <<: *analyticsDatabase
