# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: info
analytics: &analytics
  wintr/analytics/tracking:
    baseUrl: https://api-02.moengage.com
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5432/ice
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5432/ice
  messageBroker: &analyticsMessageBroker
    consumerGroup: husky-local-analytics-testing
    createTopics: true
    urls:
      - localhost:9097
    topics: &analyticsTopics
      - name: analytics-set-attributes
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: analytics-track-action
        partitions: 10
        replicationFactor: 1
        retention: 1000h
    consumingTopics:
      - name: analytics-set-attributes
        oneGoroutinePerPartition: true
      - name: analytics-track-action
        oneGoroutinePerPartition: true
analytics_test:
  <<: *analytics
  messageBroker:
    <<: *analyticsMessageBroker
    consumingTopics: *analyticsTopics
    consumerGroup: husky-analytics-testing-runner